name: oppgave 16

on:
  push:
  workflow_dispatch:

jobs:
  beratjob:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1