name: oppgave 17

on:
  push:
  workflow_dispatch:

jobs:
  beratjob:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1

      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         enable-AzPSSession: true